apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  # 使用 InitContainers 进行预配置任务
  # InitContainers 允许你在主容器启动之前运行任务。例如，你可以在主容器启动之前使用 InitContainer 安装软件包：
  initContainers:
    - name: init-container
      image: busybox
      command: [ "/bin/sh", "-c", "apt-get update && apt-get install -y mypackage" ]
  containers:
    - name: nginx-demo
      image: nginx
      # 使用环境变量
      env:
        - name: EXAMPLE_VAR
          value: example-value
      # 使用 Readiness 和 Liveness 探针进行容器健康检查
      # 就绪性和存活性探针允许你检查容器的运行状况并确保它们已准备好为流量提供服务
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
        requests:
          memory: "32Mi"
          cpu: "250m"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  